"""
Phase 11: Monte Carlo simulation for robustness analysis.

Purposes:
  1. Validate that the estimated lag can be recovered from simulated data
     generated by a known VAR(p) with planted lead-lag structure.
  2. Assess the probability of false positives (spurious Granger causality)
     under the null hypothesis of no relationship.
  3. Stress-test strategy performance under different market regimes.

Method:
  - Fit a VAR(p) to observed returns.
  - Simulate N paths from the fitted VAR.
  - Re-estimate lead-lag on each path.
  - Compare distribution of estimated lags to the planted true lag.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from config.settings import Settings
from utils.logging_utils import get_logger

log = get_logger(__name__)


class MonteCarloSimulator:
    """
    Phase 11: Monte Carlo robustness analysis for lead-lag and strategy metrics.
    """

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.rng = np.random.default_rng(settings.random_seed)

    def simulate_from_var(
        self,
        var_result,
        n_simulations: int | None = None,
        n_periods: int = 252,
    ) -> list[pd.DataFrame]:
        """
        Simulate return paths from a fitted VAR model.
        Returns a list of DataFrames, each of shape (n_periods, n_vars).
        """
        n_sim = n_simulations or self.settings.n_montecarlo
        names = var_result.names
        lag_order = var_result.k_ar
        coefs = var_result.coefs          # shape: (p, n_vars, n_vars)
        intercept = var_result.intercept  # shape: (n_vars,)
        sigma_u = var_result.sigma_u      # covariance of residuals

        # Cholesky for correlated residual simulation
        L = np.linalg.cholesky(sigma_u + 1e-8 * np.eye(sigma_u.shape[0]))

        simulations = []
        for _ in range(n_sim):
            data = np.zeros((n_periods + lag_order, len(names)))
            # Seed with zeros (could also seed with actual data)
            for t in range(lag_order, n_periods + lag_order):
                eps = L @ self.rng.standard_normal(len(names))
                y_t = intercept.copy()
                for lag in range(lag_order):
                    y_t += coefs[lag] @ data[t - lag - 1]
                y_t += eps
                data[t] = y_t
            simulations.append(
                pd.DataFrame(data[lag_order:], columns=names)
            )
        return simulations

    def false_positive_rate(
        self,
        null_returns: pd.DataFrame,
        test_fn,
        n_simulations: int | None = None,
    ) -> float:
        """
        Estimate false-positive rate under the null hypothesis.

        test_fn(source, target) → bool (True = detected significant lead-lag)
        null_returns: independent return series (shuffled, no causal structure).
        """
        n_sim = n_simulations or min(self.settings.n_bootstrap, 500)
        cols = null_returns.columns.tolist()
        fp_count = 0
        total = 0
        for _ in range(n_sim):
            for i in range(len(cols)):
                for j in range(i + 1, len(cols)):
                    # Permute column i to break any residual dependency
                    perm_src = null_returns[cols[i]].sample(
                        frac=1, random_state=self.rng.integers(0, 2**31)
                    ).reset_index(drop=True)
                    perm_src.index = null_returns.index
                    try:
                        detected = test_fn(perm_src, null_returns[cols[j]])
                        if detected:
                            fp_count += 1
                        total += 1
                    except Exception:
                        pass
        fpr = fp_count / total if total > 0 else np.nan
        log.info("False positive rate: %.4f (n=%d)", fpr, total)
        return fpr

    def rolling_window_stability(
        self,
        returns: pd.DataFrame,
        estimator_fn,
        window: int = 252,
        step: int = 21,
    ) -> pd.DataFrame:
        """
        Compute the estimator on rolling windows (walk-forward).
        Returns a DataFrame of estimates over time.
        """
        results = []
        dates = []
        for start in range(0, len(returns) - window, step):
            window_data = returns.iloc[start : start + window]
            try:
                est = estimator_fn(window_data)
                results.append(est)
            except Exception as exc:
                log.debug("Rolling estimate failed at %d: %s", start, exc)
                continue
            dates.append(returns.index[start + window - 1])

        if not results:
            return pd.DataFrame()
        if isinstance(results[0], dict):
            df = pd.DataFrame(results, index=pd.DatetimeIndex(dates))
        else:
            df = pd.Series(results, index=pd.DatetimeIndex(dates)).to_frame("estimate")
        return df
